CREATE TABLE `HealthCheck` (
  `id` VARCHAR(191) NOT NULL,
  `message` VARCHAR(191) NOT NULL DEFAULT 'teumta',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
